### ISSUE TITLE
key binding matter

### ISSUE THREAD

**Issue by eduOS** [firecat53/urlscan#26]
Hello, thanks very much for providing such a handy plugin for us. It works very well such far, setting the key binding aside, and I like all functions very well. 

As for key binding, provided that I use Tmux right now so <C-B> is a frequently used key as an operator, every time I press <C-B> it just stands still. 

So I checked which keys have not been binded except your default one, I then found <C-X>.

I don't know why you harnessed that binding since Tmux and is so widely employed, at least by Ubuntu users as I know. And could you please change it to any others.

**Comment by firecat53** [comment]
All you need to do is change the keybinding to something more convenient for you :) I also use tmux, but most people I know (myself included) change the tmux binding to ctrl-a instead of ctrl-b because it's easier to reach.

The binding in the README is completely arbitrary...I don't see a need to change it because it's not something that is even in the code. It's just a suggestion.

I appreciate your comments and your interest!

Thanks,
Scott

**Comment by eduOS** [comment]
Ok. You're right. I'd follow your setting. Thanks.
