### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by davidCarlos** [firecat53/urlscan#30]
Hey firecat53, i am packing the newest release of urlscan to Debian. I'm having a problem with bin/urlscan file. Normally this file is in the root of the project, e.g urlscan 0.5.6. I would like to know if move this file to urlscan's  dir would be a big problem to the project. 

The issue is when urlscan tries to import urlchoose and urlscan files
          ```
                from urlscan import urlchoose, urlscan
            ```
If i leave just ` import urlchoose, urlscan` and puts urlscan file inside urlscan directory, everything works well.

I checked  some python packages on Debian, and normally this script file, that in the package goes in /usr/bin/, stays in the project's root directory.

**Comment by firecat53** [comment]
I apologize but I'm having trouble understanding exactly what the issue is? Can you provide some error messages and the process you are using to package the project? Perhaps I made a packaging error but the typical layout of a python project (for example, see the [Ansible](https://github.com/ansible/ansible] project) has the actual executable file in a bin/ directory, not in the root of the project. The executable _can_ be in the project root directory, but it shouldn't matter if the package is put together correctly. 

With some more information I can help test the packaging in a VM or container.

Thanks,
Scott

**Comment by firecat53** [comment]
I did some testing today inside a Debian Jessie Docker container following the instructions [here](https://pypi.python.org/pypi/stdeb/0.8.5#quickstart-3-i-read-the-warning-so-show-me-how-to-make-a-source-package-then-compile-it) using the stdeb Python to Debian package conversion utility. Worked great, near as I can tell:

    apt-get update && apt-get install python-stdeb dh-python
    pypi-download urlscan
    py2dsc urlscan-0.8.2.tar.gz
    cd deb-dist/urlscan-0.8.2
    dpkg-buildpackage -rfakeroot -uc -us
    cd ..
    dpkg -i python-urlscan_0.8.2-1_all.deb
    apt-get -f install

Seems to install and run just fine.

Scott

**Comment by davidCarlos** [comment]
Hey Scott, i would like to apologize with you. I read with more attention debian's documentation for python packages, and found my error. The problem was that my package was not putting urlscan in pythonpath. I will make more testing with vagrant, and try to upload the package to debian.

Thanks.

**Comment by firecat53** [comment]
No worries! I'm flattered it's being packaged for Debian :) Let me know if you have other questions or issues.

Scott

**Comment by davidCarlos** [comment]
Hey Scott, 
urlscan 0.8.2 already available in debian unstable, and soon in debian testing =).

**Comment by firecat53** [comment]
Awesome, thanks!

Scott
