### ISSUE TITLE
Add shortcut to copy link

### ISSUE THREAD

**Issue by matt-snider** [firecat53/urlscan#78]
Would it be within scope of the project to add a shortcut for copying the link instead of opening it? I think this is an important feature. Currently it's not possible AFAIK to copy the link, since attempting to highlight it results in it being opened. 

I am aware of the `--run` argument, but I think copying is fundamental enough that it warrants its own permanent shortcut. Also, within the same session a user may want to open some URLs, but copy others.

**Comment by firecat53** [comment]
Added copy to clipboard with `C`. Check out the develop branch and see if it works for you. Requires xsel or xclip. Thanks!

**Comment by matt-snider** [comment]
@firecat53 Awesome! That's great :+1: 

One thing you might consider is using the `XA_CLIPBOARD` since that is the one used by most applications for `Ctrl+X`/`Ctrl+C`/`Ctrl+V`.  I commented about that on the commit [here](https://github.com/firecat53/urlscan/commit/5c8c0f4e48031130a15e2cc1a15a3cc37d75cba0#r32014556). But different people might have other opinions on this. You could also make it configurable. 

Either way, works for me :smile:

**Comment by firecat53** [comment]
Valid consideration. I don't know the right answer as to which clipboard to use. My inclination is to use primary, since urlscan users are most likely to be more advanced and conversant in terminal/clipboard usage. I could make it configurable, but I think I'll leave it as primary for now for simplicity's sake unless for some reason I get a large number (hahaha) of people requesting the clipboard instead.

**Comment by matt-snider** [comment]
Sounds good to me. Seeing as this appears to be the first request for clipboard support, I think keeping it simple is a good choice. Thank you for implementing this!
