### ISSUE TITLE
Starting a new browser instance blocks mutt

### ISSUE THREAD

**Issue by clwgg** [firecat53/urlscan#85]
Hi,
I have a problem, where opening a link through urlscan blocks the terminal mutt is running in, if no browser was running before (i.e. opening the link started a new browser instance). If a browser is running already and the link is opened as a new tab, the terminal is not blocked.

I suspect this is not the expected behavior, but I can't seem to figure out what's going wrong. Any help would be appreciated.

Some more info on my system:
- Manjaro Linux with i3-wm
- neomutt 20180716-7, but same behaviour in mutt 1.11.4-1
- urlscan 0.9.2-1
- python 3.7.2
- problem exists for both firefox and chromium
- rxvt-unicode 9.22-7 terminal emulator

**Comment by firecat53** [comment]
Interesting...I never noticed that before because I use a small wrapper script that launches either GUI or text browser depending on if I'm in X or not. I also always have my browser open, so I never saw the difference in behavior with the browser initially closed. After some research, Mutt doesn't handle backgrounding applications that are launched from the .mailcap or things like urlscan.

In any case, this wrapper script should work for you (edit your desired browser). `export BROWSER=browser.sh` in your .bashrc or .profile or .bash_profile.

    #!/bin/bash
    # Chooses default CLI or GUI browser

    browser_cli="elinks"
    browser="qutebrowser"

    if [ -z "$DISPLAY" ]; then
        eval "$browser_cli" "$@" &> /dev/null &
    else
        eval "$browser" "$@" &> /dev/null &
    fi

**Comment by clwgg** [comment]
Cool, that works -- thanks a lot for the help!
